"""add day_type in educational_courses

Revision ID: 25da8d84384a
Revises: 1dbc399cf62a
Create Date: 2024-12-12 16:56:31.000893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25da8d84384a'
down_revision: Union[str, None] = '1dbc399cf62a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('educational_courses', sa.Column('day_type', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('educational_courses', 'day_type')
    # ### end Alembic commands ###
