"""Add unique constraint on classes_id and subjects_id

Revision ID: 37db3d4ad11a
Revises: 5b7117fcf889
Create Date: 2024-12-12 20:45:07.628550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37db3d4ad11a'
down_revision: Union[str, None] = '5b7117fcf889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_classes_subjects', 'assignments_subjects', ['classes_id', 'subjects_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_classes_subjects', 'assignments_subjects', type_='unique')
    # ### end Alembic commands ###
