"""Add sessions_subjects table with relationships

Revision ID: 5b7117fcf889
Revises: fb4af891b9e8
Create Date: 2024-12-12 16:30:21.221382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7117fcf889'
down_revision: Union[str, None] = 'fb4af891b9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classrooms_id', sa.Integer(), nullable=True),
    sa.Column('assignments_subjects_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Confirmed', 'Refused', name='status_enum'), nullable=False),
    sa.Column('start_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('end_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['assignments_subjects_id'], ['assignments_subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['classrooms_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_subjects_id'), 'sessions_subjects', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_subjects_id'), table_name='sessions_subjects')
    op.drop_table('sessions_subjects')
    # ### end Alembic commands ###
