"""Update educational_courses to remove description field and add unique constraint to day field

Revision ID: 8ef15c74d764
Revises: 9bdc8bf032c9
Create Date: 2024-12-15 13:07:50.125686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ef15c74d764'
down_revision: Union[str, None] = '9bdc8bf032c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('day_type')
    op.create_unique_constraint(None, 'educational_courses', ['day'])
    op.drop_column('educational_courses', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('educational_courses', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'educational_courses', type_='unique')
    op.create_table('day_type',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='day_type_pkey')
    )
    # ### end Alembic commands ###
