"""Add assignments_courses table

Revision ID: 97f7f6c19239
Revises: 8ebfc2185d8f
Create Date: 2024-12-12 00:07:56.161427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97f7f6c19239'
down_revision: Union[str, None] = '8ebfc2185d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classes_id', sa.Integer(), nullable=False),
    sa.Column('courses_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('url_online', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['classes_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['courses_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['users_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_courses_id'), 'assignments_courses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignments_courses_id'), table_name='assignments_courses')
    op.drop_table('assignments_courses')
    # ### end Alembic commands ###
