"""Update availability model by adding slots field and backref to user model

Revision ID: 9bdc8bf032c9
Revises: 0fe65c4999a0
Create Date: 2024-12-14 20:39:41.436371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9bdc8bf032c9'
down_revision: Union[str, None] = '0fe65c4999a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availabilities', sa.Column('slots', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('availabilities', 'comment')
    op.drop_column('availabilities', 'end_at')
    op.drop_column('availabilities', 'start_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availabilities', sa.Column('start_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('availabilities', sa.Column('end_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('availabilities', sa.Column('comment', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('availabilities', 'slots')
    # ### end Alembic commands ###
