"""classes

Revision ID: d8208c15e571
Revises: 37e92dd165df
Create Date: 2024-12-11 17:57:34.170485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8208c15e571'
down_revision: Union[str, None] = '37e92dd165df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('educational_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('years_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('number_students', sa.Integer(), nullable=False),
    sa.Column('years_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['years_group_id'], ['years_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('years_groups_educational_courses',
    sa.Column('years_group_id', sa.Integer(), nullable=False),
    sa.Column('educational_courses_id', sa.Integer(), nullable=False),
    sa.Column('day_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day_type_id'], ['day_type.id'], ),
    sa.ForeignKeyConstraint(['educational_courses_id'], ['educational_courses.id'], ),
    sa.ForeignKeyConstraint(['years_group_id'], ['years_groups.id'], ),
    sa.PrimaryKeyConstraint('years_group_id', 'educational_courses_id')
    )
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_table('years_groups_educational_courses')
    op.drop_table('classes')
    op.drop_table('years_groups')
    op.drop_table('educational_courses')
    op.drop_table('day_type')
    # ### end Alembic commands ###
