from decouple import config

POSTGRES_URL = config('POSTGRES_URL')
SECRET_KEY= config('SECRET_KEY')
ALGORITHM = config('HASH_ALGORITHM')
ACCESS_TOKEN_EXPIRE_MINUTES= config('ACCESS_TOKEN_EXPIRE_MINUTES')